jwt:
  secret: '[a-zA-Z0-9._]^+$GuidelinAurorees8SaisonAfricaSaisonlesmeilleursushherforAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8285
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagementsystem?serverTimezone=UTC #change this to your database url
    password:  #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false

